
services:
  backend:
    build: ./backend
    restart: always
    environment:
      - FOTOS_PATH=/fotos
      - TZ=America/Sao_Paulo
      # Defina as origens permitidas pelo CORS (frontend URL)
      - ALLOWED_ORIGINS=http://localhost:8090
    volumes:
      - ./fotos:/fotos
    ports:
      - "8000:8000"
    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./fotos:/fotos:ro
    depends_on:
      - backend
