version: '3.9'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      FOTOS_PATH: /fotos
    volumes:
      - ./fotos:/fotos
    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fotos:/fotos:ro
    depends_on:
      - backend
      - frontend
